#### generated by claude

import streamlit as st
import torch
import re
import pandas as pd
from io import StringIO
from PIL import Image
from transformers import AutoProcessor, AutoModelForImageTextToText

# ─── Page Config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Granite Vision",
    page_icon="🔬",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── Custom CSS ───────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Syne:wght@400;600;800&display=swap');

/* ── Root Variables ── */
:root {
    --bg:        #0a0a0f;
    --surface:   #12121a;
    --border:    #1e1e2e;
    --accent:    #6c63ff;
    --accent2:   #00d4aa;
    --text:      #e8e8f0;
    --muted:     #6b6b80;
    --mono:      'Space Mono', monospace;
    --sans:      'Syne', sans-serif;
}

/* ── Global ── */
html, body, [class*="css"] {
    background-color: var(--bg) !important;
    color: var(--text) !important;
    font-family: var(--sans) !important;
}

/* ── Header ── */
.granite-header {
    display: flex;
    align-items: center;
    gap: 1rem;
    padding: 2rem 0 1rem;
    border-bottom: 1px solid var(--border);
    margin-bottom: 2rem;
}
.granite-logo {
    width: 48px; height: 48px;
    background: linear-gradient(135deg, var(--accent), var(--accent2));
    border-radius: 12px;
    display: flex; align-items: center; justify-content: center;
    font-size: 1.5rem;
    flex-shrink: 0;
}
.granite-title { margin: 0; font-size: 1.8rem; font-weight: 800; letter-spacing: -0.03em; }
.granite-sub   { margin: 0; font-size: 0.8rem; color: var(--muted); font-family: var(--mono); }
.accent  { color: var(--accent); }
.accent2 { color: var(--accent2); }

/* ── Cards ── */
.card {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 16px;
    padding: 1.5rem;
    margin-bottom: 1.2rem;
    transition: border-color .2s;
}
.card:hover { border-color: var(--accent); }
.card-label {
    font-family: var(--mono);
    font-size: 0.65rem;
    letter-spacing: .12em;
    color: var(--muted);
    text-transform: uppercase;
    margin-bottom: .6rem;
}

/* ── Mode Pill ── */
.mode-pill {
    display: inline-block;
    background: linear-gradient(135deg, var(--accent)22, var(--accent2)22);
    border: 1px solid var(--accent);
    border-radius: 20px;
    padding: .25rem .85rem;
    font-size: .75rem;
    font-family: var(--mono);
    color: var(--accent2);
    margin-bottom: 1rem;
}

/* ── Result Box ── */
.result-box {
    background: #0d0d18;
    border: 1px solid var(--border);
    border-left: 3px solid var(--accent2);
    border-radius: 8px;
    padding: 1.2rem;
    font-family: var(--mono);
    font-size: .82rem;
    line-height: 1.7;
    white-space: pre-wrap;
    word-break: break-word;
    max-height: 500px;
    overflow-y: auto;
}

/* ── Sidebar ── */
section[data-testid="stSidebar"] {
    background: var(--surface) !important;
    border-right: 1px solid var(--border) !important;
}
section[data-testid="stSidebar"] * { color: var(--text) !important; }

/* ── Buttons ── */
.stButton > button {
    background: linear-gradient(135deg, var(--accent), var(--accent2)) !important;
    color: #fff !important;
    border: none !important;
    border-radius: 10px !important;
    font-family: var(--mono) !important;
    font-size: .82rem !important;
    letter-spacing: .06em !important;
    padding: .6rem 1.4rem !important;
    width: 100% !important;
    transition: opacity .2s !important;
}
.stButton > button:hover { opacity: .85 !important; }

/* ── File uploader ── */
[data-testid="stFileUploader"] {
    background: var(--surface) !important;
    border: 1px dashed var(--border) !important;
    border-radius: 12px !important;
}

/* ── Select / Text area ── */
.stSelectbox > div > div,
.stTextArea > div > div {
    background: var(--surface) !important;
    border-color: var(--border) !important;
    border-radius: 10px !important;
    color: var(--text) !important;
    font-family: var(--mono) !important;
}

/* ── Spinner ── */
.stSpinner > div { border-top-color: var(--accent) !important; }

/* ── Tables ── */
.stDataFrame { border-radius: 10px; overflow: hidden; }

/* ── Stat badge ── */
.stat-row { display: flex; gap: .8rem; flex-wrap: wrap; margin-bottom: 1rem; }
.stat-badge {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: .4rem .9rem;
    font-family: var(--mono);
    font-size: .72rem;
    color: var(--muted);
}
.stat-badge span { color: var(--accent2); font-weight: 700; }

/* ── Hide default Streamlit chrome ── */
#MainMenu, footer, header { visibility: hidden; }
</style>
""", unsafe_allow_html=True)


# ─── Model Loading ─────────────────────────────────────────────────────────────
@st.cache_resource(show_spinner=False)
def load_model():
    model_id = "ibm-granite/granite-4.0-3b-vision"
    device = "cuda" if torch.cuda.is_available() else "cpu"
    processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
    model = AutoModelForImageTextToText.from_pretrained(
        model_id,
        trust_remote_code=True,
        torch_dtype=torch.bfloat16,
        device_map=device,
    ).eval()
    model.merge_lora_adapters()
    return model, processor, device


# ─── Inference ────────────────────────────────────────────────────────────────
def run_inference(model, processor, image: Image.Image, prompt: str) -> str:
    conversation = [
        {"role": "user", "content": [
            {"type": "image"},
            {"type": "text", "text": prompt},
        ]}
    ]
    text = processor.apply_chat_template(
        conversation, tokenize=False, add_generation_prompt=True
    )
    inputs = processor(
        text=[text], images=[image], return_tensors="pt", padding=True, do_pad=True
    ).to(model.device)
    output = model.generate(**inputs, max_new_tokens=4096, use_cache=True)
    gen = output[0, inputs["input_ids"].shape[1]:]
    return processor.decode(gen, skip_special_tokens=True)


# ─── Helpers ──────────────────────────────────────────────────────────────────
MODES = {
    "📊 Chart → Summary":   ("chart_summary",  "Describe this chart in detail. Explain the axes, trends, key data points, and any notable insights."),
    "📋 Chart → CSV":       ("chart_csv",       "Extract all data points from this chart and return them as a CSV with headers. Wrap the CSV in ```csv``` code fences."),
    "🗂 Table → HTML":      ("table_html",      "<tables_html>"),
    "✏️ Custom Prompt":     ("custom",          ""),
}

def extract_csv(text: str) -> pd.DataFrame | None:
    m = re.search(r"```csv\s*(.*?)```", text, re.DOTALL)
    if m:
        try:
            return pd.read_csv(StringIO(m.group(1)))
        except Exception:
            return None
    return None

def extract_html_table(text: str) -> pd.DataFrame | None:
    if "<table" in text.lower():
        try:
            return pd.read_html(StringIO(text))[0]
        except Exception:
            return None
    return None


# ─── Header ───────────────────────────────────────────────────────────────────
st.markdown("""
<div class="granite-header">
    <div class="granite-logo">🔬</div>
    <div>
        <p class="granite-title"><span class="accent">Granite</span> <span class="accent2">Vision</span></p>
        <p class="granite-sub">ibm-granite/granite-4.0-3b-vision · image-text-to-text</p>
    </div>
</div>
""", unsafe_allow_html=True)


# ─── Sidebar ──────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### ⚙️ Settings")
    st.markdown("---")

    mode_label = st.selectbox("Analysis Mode", list(MODES.keys()))
    mode_key, default_prompt = MODES[mode_label]

    if mode_key == "custom":
        custom_prompt = st.text_area("Your Prompt", height=120,
                                     placeholder="Ask anything about the image…")
        final_prompt = custom_prompt
    else:
        final_prompt = default_prompt
        with st.expander("Prompt (auto-generated)", expanded=False):
            st.code(final_prompt, language="text")

    st.markdown("---")
    max_tokens = st.slider("Max New Tokens", 256, 4096, 2048, step=128)
    st.markdown("---")
    st.markdown(
        '<p style="font-family:\'Space Mono\',monospace;font-size:.65rem;color:#6b6b80;">'
        'Built with 🤍 using IBM Granite 4.0<br>Streamlit · Transformers · PyTorch</p>',
        unsafe_allow_html=True,
    )


# ─── Main Layout ──────────────────────────────────────────────────────────────
col_left, col_right = st.columns([1, 1.4], gap="large")

with col_left:
    st.markdown('<div class="card-label">Upload Image</div>', unsafe_allow_html=True)
    uploaded = st.file_uploader(
        "Drop an image here", type=["png", "jpg", "jpeg", "webp", "bmp"],
        label_visibility="collapsed",
    )

    if uploaded:
        img = Image.open(uploaded).convert("RGB")
        st.image(img, use_container_width=True, caption=uploaded.name)
        w, h = img.size
        st.markdown(f"""
        <div class="stat-row">
            <div class="stat-badge">W <span>{w}px</span></div>
            <div class="stat-badge">H <span>{h}px</span></div>
            <div class="stat-badge">Mode <span>{img.mode}</span></div>
        </div>""", unsafe_allow_html=True)

    run_btn = st.button("▶ Run Inference", disabled=not uploaded)


with col_right:
    st.markdown(f'<div class="mode-pill">{mode_label}</div>', unsafe_allow_html=True)

    if "result" not in st.session_state:
        st.session_state.result = None
        st.session_state.last_mode = None

    if run_btn and uploaded:
        with st.spinner("Loading model…"):
            model, processor, device = load_model()

        st.markdown(f"""
        <div class="stat-row">
            <div class="stat-badge">Device <span>{device.upper()}</span></div>
            <div class="stat-badge">Model <span>granite-4.0-3b-vision</span></div>
        </div>""", unsafe_allow_html=True)

        prompt_to_use = final_prompt if mode_key != "custom" else custom_prompt
        if not prompt_to_use.strip():
            st.warning("Please enter a prompt first.")
        else:
            with st.spinner("Running inference…"):
                result = run_inference(model, processor, img, prompt_to_use)
            st.session_state.result = result
            st.session_state.last_mode = mode_key

    if st.session_state.result:
        result = st.session_state.result
        mode_k  = st.session_state.last_mode

        # ── Structured output for CSV ──
        if mode_k == "chart_csv":
            df = extract_csv(result)
            if df is not None:
                st.markdown('<div class="card-label">Extracted Table</div>', unsafe_allow_html=True)
                st.dataframe(df, use_container_width=True)
                csv_bytes = df.to_csv(index=False).encode()
                st.download_button("⬇ Download CSV", csv_bytes, "extracted.csv", "text/csv")
            st.markdown('<div class="card-label">Raw Output</div>', unsafe_allow_html=True)
            st.markdown(f'<div class="result-box">{result}</div>', unsafe_allow_html=True)

        # ── Structured output for HTML table ──
        elif mode_k == "table_html":
            df = extract_html_table(result)
            if df is not None:
                st.markdown('<div class="card-label">Parsed Table</div>', unsafe_allow_html=True)
                st.dataframe(df, use_container_width=True)
            st.markdown('<div class="card-label">HTML Output</div>', unsafe_allow_html=True)
            with st.expander("Raw HTML", expanded=False):
                st.code(result, language="html")
            st.markdown("**Rendered:**")
            st.components.v1.html(result, height=400, scrolling=True)

        # ── Plain text summary / custom ──
        else:
            st.markdown('<div class="card-label">Analysis Result</div>', unsafe_allow_html=True)
            st.markdown(f'<div class="result-box">{result}</div>', unsafe_allow_html=True)
            st.download_button("⬇ Download Text", result.encode(), "result.txt", "text/plain")
