### NOTE : Front End Code Generated by Claude

import streamlit as st
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from transformers import AutoTokenizer
import onnxruntime as ort

# ─── Page Config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="pplx-embed · Similarity Explorer",
    page_icon="🔮",
    layout="wide",
)

# ─── Custom CSS ─────────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=DM+Sans:wght@300;400;500;600&display=swap');

/* Root theme */
:root {
    --bg: #0b0f19;
    --surface: #131929;
    --surface2: #1a2236;
    --border: #1f2d45;
    --accent: #4f8ef7;
    --accent2: #a78bfa;
    --green: #34d399;
    --yellow: #fbbf24;
    --red: #f87171;
    --text: #e2e8f0;
    --muted: #64748b;
}

html, body, [data-testid="stAppViewContainer"] {
    background-color: var(--bg) !important;
    color: var(--text) !important;
    font-family: 'DM Sans', sans-serif;
}

[data-testid="stSidebar"] {
    background-color: var(--surface) !important;
    border-right: 1px solid var(--border);
}

/* Header */
.hero {
    text-align: center;
    padding: 2.5rem 0 1.5rem;
    border-bottom: 1px solid var(--border);
    margin-bottom: 2rem;
}
.hero h1 {
    font-family: 'Space Mono', monospace;
    font-size: 2.2rem;
    font-weight: 700;
    background: linear-gradient(135deg, var(--accent), var(--accent2));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin: 0 0 0.4rem;
}
.hero p {
    color: var(--muted);
    font-size: 0.95rem;
    margin: 0;
}

/* Stat cards */
.stat-row { display: flex; gap: 1rem; margin-bottom: 1.5rem; }
.stat-card {
    flex: 1;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 1rem 1.25rem;
}
.stat-label { font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.08em; color: var(--muted); margin-bottom: 0.25rem; }
.stat-value { font-family: 'Space Mono', monospace; font-size: 1.6rem; font-weight: 700; color: var(--text); }
.stat-sub { font-size: 0.78rem; color: var(--muted); margin-top: 0.15rem; }

/* Score badge */
.badge {
    display: inline-block;
    font-family: 'Space Mono', monospace;
    font-size: 0.78rem;
    font-weight: 700;
    padding: 0.2rem 0.55rem;
    border-radius: 5px;
}

/* Text pills */
.text-pill {
    background: var(--surface2);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 0.5rem 0.9rem;
    margin: 0.3rem 0;
    font-size: 0.88rem;
    color: var(--text);
}
.text-pill-num {
    font-family: 'Space Mono', monospace;
    font-size: 0.72rem;
    color: var(--accent);
    margin-right: 0.5rem;
}

/* Section header */
.sec-head {
    font-family: 'Space Mono', monospace;
    font-size: 0.78rem;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    color: var(--muted);
    margin: 1.5rem 0 0.75rem;
    border-bottom: 1px solid var(--border);
    padding-bottom: 0.4rem;
}

/* Streamlit overrides */
div[data-testid="stTextArea"] textarea {
    background: var(--surface2) !important;
    border: 1px solid var(--border) !important;
    color: var(--text) !important;
    font-family: 'DM Sans', sans-serif !important;
    font-size: 0.9rem !important;
    border-radius: 8px !important;
}
div[data-testid="stTextArea"] textarea:focus {
    border-color: var(--accent) !important;
    box-shadow: 0 0 0 2px rgba(79,142,247,0.15) !important;
}
button[kind="primary"] {
    background: linear-gradient(135deg, var(--accent), var(--accent2)) !important;
    border: none !important;
    font-family: 'Space Mono', monospace !important;
    font-size: 0.85rem !important;
    letter-spacing: 0.05em !important;
    border-radius: 8px !important;
    padding: 0.5rem 1.5rem !important;
}
[data-testid="stSelectbox"] > div {
    background: var(--surface2) !important;
    border-color: var(--border) !important;
}
label, .stSelectbox label, .stTextArea label {
    color: var(--muted) !important;
    font-size: 0.8rem !important;
    text-transform: uppercase !important;
    letter-spacing: 0.07em !important;
}
[data-testid="stAlert"] {
    border-radius: 8px !important;
}
</style>
""", unsafe_allow_html=True)


# ─── Backend ─────────────────────────────────────────────────────────────────────
class Pplx_Embed:
    def __init__(self, model_name="perplexity-ai/pplx-embed-v1-0.6b", onnx_model_path="model (1).onnx"):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
        self.session = ort.InferenceSession(onnx_model_path)

    def cosine_similarity(self, vec1, vec2):
        vec1, vec2 = np.array(vec1), np.array(vec2)
        return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

    def embed(self, texts):
        tokenized = self.tokenizer(texts, padding=True, truncation=True, return_tensors="np")
        onnx_inputs = {
            "input_ids": tokenized["input_ids"].astype(np.int64),
            "attention_mask": tokenized["attention_mask"].astype(np.int64),
        }
        onnx_embeddings = self.session.run([o.name for o in self.session.get_outputs()], onnx_inputs)
        attention_mask = onnx_inputs["attention_mask"]
        embeddings = onnx_embeddings[0]
        masked = embeddings * attention_mask[:, :, None]
        sum_emb = masked.sum(axis=1)
        lengths = attention_mask.sum(axis=1)[:, None]
        return sum_emb / lengths

    def get_score(self, texts):
        embeds = self.embed(texts)
        return {
            q_txt: {
                v_txt: float(self.cosine_similarity(q_embed, v_embed))
                for v_embed, v_txt in zip(embeds, texts) if q_txt != v_txt
            }
            for q_embed, q_txt in zip(embeds, texts)
        }


@st.cache_resource(show_spinner=False)
def load_model():
    return Pplx_Embed()


# ─── Helpers ─────────────────────────────────────────────────────────────────────
def score_color(s):
    if s >= 0.75: return "#34d399"
    if s >= 0.55: return "#4f8ef7"
    if s >= 0.40: return "#fbbf24"
    return "#f87171"

def short(text, n=38):
    return text if len(text) <= n else text[:n] + "…"

def build_matrix(scores, texts):
    n = len(texts)
    mat = np.zeros((n, n))
    for i, t1 in enumerate(texts):
        for j, t2 in enumerate(texts):
            if i == j:
                mat[i][j] = 1.0
            elif t2 in scores.get(t1, {}):
                mat[i][j] = scores[t1][t2]
    return mat


# ─── UI ──────────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="hero">
  <h1>pplx-embed · Similarity Explorer</h1>
  <p>Semantic similarity powered by <code>perplexity-ai/pplx-embed-v1-0.6b</code> · ONNX Runtime</p>
</div>
""", unsafe_allow_html=True)

# ── Sidebar ──────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### ⚙️ Settings")
    # onnx_path = st.text_input("ONNX model path", value="model (1).onnx")
    viz_mode = st.selectbox("Default chart", ["Heatmap", "Bar Chart", "Both"])
    st.markdown("---")
    st.markdown("#### Sample texts")
    if st.button("Load samples"):
        st.session_state["sample_loaded"] = True

SAMPLES = """\
Scientists explore the universe driven by curiosity.
Children learn through curious exploration.
Historical discoveries began with curious questions.
Animals use curiosity to adapt and survive.
Philosophy examines the nature of curiosity.\
"""

# ── Input ─────────────────────────────────────────────────────────────────────────
default_val = SAMPLES if st.session_state.get("sample_loaded") else ""
raw = st.text_area(
    "Enter texts (one per line, minimum 2)",
    value=default_val,
    height=180,
    placeholder="Type or paste sentences here, one per line…",
)

col_btn, col_info = st.columns([1, 4])
with col_btn:
    run = st.button("▶ Compute", type="primary", use_container_width=True)

texts = [t.strip() for t in raw.strip().splitlines() if t.strip()]

# ── Compute ────────────────────────────────────────────────────────────────────────
if run:
    if len(texts) < 2:
        st.error("Please enter at least 2 sentences.")
    else:
        with st.spinner("Loading model & computing embeddings…"):
            try:
                model = load_model()
                scores = model.get_score(texts)
                st.session_state["scores"] = scores
                st.session_state["texts"] = texts
            except Exception as e:
                st.error(f"Error: {e}")

# ── Results ────────────────────────────────────────────────────────────────────────
if "scores" in st.session_state:
    scores = st.session_state["scores"]
    texts  = st.session_state["texts"]
    n = len(texts)

    # Flat pairs
    pairs = [(t1, t2, s) for t1, inner in scores.items() for t2, s in inner.items()]
    all_scores = [s for *_, s in pairs]
    avg_s = np.mean(all_scores)
    max_pair = max(pairs, key=lambda x: x[2])
    min_pair = min(pairs, key=lambda x: x[2])

    # ── Stat cards
    st.markdown(f"""
    <div class="stat-row">
      <div class="stat-card">
        <div class="stat-label">Sentences</div>
        <div class="stat-value">{n}</div>
        <div class="stat-sub">{n*(n-1)} unique pairs</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Avg Similarity</div>
        <div class="stat-value" style="color:{score_color(avg_s)}">{avg_s:.4f}</div>
        <div class="stat-sub">across all pairs</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Highest</div>
        <div class="stat-value" style="color:#34d399">{max_pair[2]:.4f}</div>
        <div class="stat-sub">{short(max_pair[0])} ↔ {short(max_pair[1])}</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Lowest</div>
        <div class="stat-value" style="color:#f87171">{min_pair[2]:.4f}</div>
        <div class="stat-sub">{short(min_pair[0])} ↔ {short(min_pair[1])}</div>
      </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Text index legend
    st.markdown('<div class="sec-head">Text Index</div>', unsafe_allow_html=True)
    for i, t in enumerate(texts):
        st.markdown(f'<div class="text-pill"><span class="text-pill-num">T{i+1}</span>{t}</div>', unsafe_allow_html=True)

    # ── Charts
    labels = [f"T{i+1}" for i in range(n)]
    mat = build_matrix(scores, texts)

    plotly_layout = dict(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(family="DM Sans", color="#e2e8f0", size=12),
        margin=dict(l=20, r=20, t=40, b=20),
    )

    show_heat = viz_mode in ("Heatmap", "Both")
    show_bar  = viz_mode in ("Bar Chart", "Both")

    if show_heat and show_bar:
        col1, col2 = st.columns([3, 2])
    elif show_heat:
        col1 = st.container()
        col2 = None
    else:
        col1 = None
        col2 = st.container()

    # Heatmap
    if show_heat:
        with col1:
            st.markdown('<div class="sec-head">Similarity Heatmap</div>', unsafe_allow_html=True)
            hover = [[
                f"<b>{texts[i]}</b><br>↔<br><b>{texts[j]}</b><br>Score: {mat[i][j]:.4f}"
                for j in range(n)] for i in range(n)]
            fig_heat = go.Figure(go.Heatmap(
                z=mat, x=labels, y=labels,
                text=[[f"{mat[i][j]:.3f}" for j in range(n)] for i in range(n)],
                texttemplate="%{text}",
                hovertext=hover, hoverinfo="text",
                colorscale=[
                    [0.0, "#1a2236"], [0.4, "#1e3a5f"],
                    [0.6, "#1d4ed8"], [0.8, "#4f8ef7"],
                    [1.0, "#34d399"],
                ],
                zmin=0, zmax=1,
                showscale=True,
                colorbar=dict(tickfont=dict(color="#64748b"), thickness=12, len=0.8),
            ))
            fig_heat.update_layout(**plotly_layout, height=380)
            fig_heat.update_xaxes(showgrid=False, tickfont=dict(color="#a78bfa", family="Space Mono"))
            fig_heat.update_yaxes(showgrid=False, tickfont=dict(color="#a78bfa", family="Space Mono"))
            st.plotly_chart(fig_heat, use_container_width=True)

    # Bar chart (top pairs)
    if show_bar:
        with col2:
            st.markdown('<div class="sec-head">Top Pairs</div>', unsafe_allow_html=True)
            unique_pairs = []
            seen = set()
            for t1, t2, s in sorted(pairs, key=lambda x: -x[2]):
                key = frozenset([t1, t2])
                if key not in seen:
                    seen.add(key)
                    i = texts.index(t1)
                    j = texts.index(t2)
                    unique_pairs.append((f"T{i+1}↔T{j+1}", s, score_color(s)))

            bar_labels = [p[0] for p in unique_pairs]
            bar_vals   = [p[1] for p in unique_pairs]
            bar_colors = [p[2] for p in unique_pairs]

            fig_bar = go.Figure(go.Bar(
                x=bar_vals, y=bar_labels,
                orientation="h",
                marker=dict(color=bar_colors, line=dict(width=0)),
                hovertemplate="<b>%{y}</b><br>Score: %{x:.4f}<extra></extra>",
                text=[f"{v:.3f}" for v in bar_vals],
                textposition="outside",
                textfont=dict(family="Space Mono", size=10, color="#e2e8f0"),
            ))
            fig_bar.update_layout(
                **plotly_layout,
                height=380,
                xaxis=dict(range=[0, 1.05], showgrid=True, gridcolor="#1f2d45", tickfont=dict(color="#64748b")),
                yaxis=dict(showgrid=False, tickfont=dict(color="#a78bfa", family="Space Mono")),
                bargap=0.3,
            )
            st.plotly_chart(fig_bar, use_container_width=True)

    # ── Per-query drill-down
    st.markdown('<div class="sec-head">Query Drill-down</div>', unsafe_allow_html=True)
    query_labels = [f"T{i+1}: {short(t, 55)}" for i, t in enumerate(texts)]
    selected = st.selectbox("Select a query sentence", query_labels)
    sel_idx  = query_labels.index(selected)
    sel_text = texts[sel_idx]

    inner = scores[sel_text]
    sorted_inner = sorted(inner.items(), key=lambda x: -x[1])

    for v_text, score in sorted_inner:
        j = texts.index(v_text)
        color = score_color(score)
        bar_w = int(score * 100)
        st.markdown(f"""
        <div style="background:#131929;border:1px solid #1f2d45;border-radius:10px;padding:0.85rem 1.1rem;margin-bottom:0.6rem;">
          <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:0.5rem;">
            <span style="font-size:0.88rem;color:#e2e8f0">
              <span style="font-family:'Space Mono',monospace;color:#a78bfa;font-size:0.75rem;margin-right:0.4rem">T{j+1}</span>{v_text}
            </span>
            <span class="badge" style="background:{color}22;color:{color};border:1px solid {color}44">{score:.4f}</span>
          </div>
          <div style="background:#0b0f19;border-radius:4px;height:6px;overflow:hidden;">
            <div style="width:{bar_w}%;height:100%;background:linear-gradient(90deg,{color}88,{color});border-radius:4px;transition:width 0.4s ease;"></div>
          </div>
        </div>
        """, unsafe_allow_html=True)

    # ── Raw scores table
    with st.expander("📋 Raw scores table"):
        df = pd.DataFrame(mat, index=labels, columns=labels).round(4)
        st.dataframe(df, use_container_width=True)
