### Generated by ChatGPT
import streamlit as st
import os
import time
from backend import LuxTTSBackend

# Page config
st.set_page_config(page_title="LuxTTS Voice Cloner", layout="centered")

st.title("🎙️ LuxTTS Voice Cloner")
st.write("Upload a reference audio and generate cloned speech.")

# Initialize model once
@st.cache_resource
def load_model():
    return LuxTTSBackend()

model = load_model()

# Upload reference audio
uploaded_file = st.file_uploader(
    "Upload Reference Audio",
    type=["wav", "mp3"]
)

if uploaded_file is not None:
    # Save uploaded file
    ref_audio_path = "reference.wav"
    with open(ref_audio_path, "wb") as f:
        f.write(uploaded_file.read())

    st.subheader("🔊 Reference Audio")
    st.audio(ref_audio_path)

    # Text input
    text = st.text_area("Enter text to generate speech:")

    if st.button("Generate Speech"):
        if text.strip() == "":
            st.warning("Please enter some text.")
        else:
            with st.spinner("Generating speech..."):
                output_path = "output.wav"
                s = time.time()
                model.tts(ref_audio_path, text, output_path)
                total_time_taken = int(time.time() - s)

            st.success(f"Speech generated successfully total time taken {total_time_taken} seconds !")

            st.subheader("🎧 Generated Audio")
            st.audio(output_path)
