### NOTE : Generated by clude

import streamlit as st
from PIL import Image
import tempfile
import os
import time

# ── Import user's backend ──────────────────────────────────────────────────────
from ocr import OCR  # assumes ocr.py is in the same directory

# ── Page config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Qianfan-OCR",
    page_icon="⬡",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ── Styles ─────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Mono:ital,wght@0,300;0,400;0,500;1,300&display=swap');

*, html, body, [class*="css"] {
    font-family: 'DM Mono', monospace;
    box-sizing: border-box;
}

.stApp { background: #f5f2ec; }
#MainMenu, footer, header { visibility: hidden; }
.block-container { padding: 3rem 3.5rem 5rem; max-width: 1280px; }

/* ── Top bar ── */
.topbar {
    display: flex;
    align-items: baseline;
    justify-content: space-between;
    margin-bottom: 3rem;
    padding-bottom: 1.2rem;
    border-bottom: 1.5px solid #1a1a1a;
}
.topbar-title {
    font-family: 'Syne', sans-serif;
    font-size: 2rem;
    font-weight: 800;
    color: #1a1a1a;
    letter-spacing: -1px;
}
.topbar-title span { color: #c8f53c; background: #1a1a1a; padding: 0 6px; border-radius: 3px; }
.topbar-meta {
    font-size: 0.72rem;
    color: #888;
    letter-spacing: 0.5px;
}

/* ── Section label ── */
.sec-label {
    font-size: 0.65rem;
    font-weight: 500;
    letter-spacing: 2.5px;
    text-transform: uppercase;
    color: #999;
    margin-bottom: 0.7rem;
}

/* ── Upload card ── */
[data-testid="stFileUploader"] {
    background: #fff !important;
    border: 1.5px dashed #bbb !important;
    border-radius: 10px !important;
    padding: 0.5rem !important;
}
[data-testid="stFileUploader"]:hover { border-color: #1a1a1a !important; }
[data-testid="stFileUploader"] span,
[data-testid="stFileUploader"] p,
[data-testid="stFileUploader"] small,
[data-testid="stFileDropzoneInstructions"] span,
[data-testid="stFileDropzoneInstructions"] small {
    color: #333 !important;
    font-family: 'DM Mono', monospace !important;
    font-size: 0.78rem !important;
}

/* ── Quick prompt pills ── */
.stButton > button {
    background: #fff !important;
    border: 1.5px solid #ddd !important;
    color: #333 !important;
    font-family: 'DM Mono', monospace !important;
    font-size: 0.72rem !important;
    border-radius: 999px !important;
    padding: 0.35rem 0.9rem !important;
    transition: all 0.15s !important;
    white-space: nowrap !important;
}
.stButton > button:hover {
    border-color: #1a1a1a !important;
    background: #1a1a1a !important;
    color: #c8f53c !important;
}

/* ── Run button override ── */
.run-btn > button {
    background: #1a1a1a !important;
    border: none !important;
    color: #c8f53c !important;
    font-family: 'Syne', sans-serif !important;
    font-weight: 700 !important;
    font-size: 0.9rem !important;
    letter-spacing: 0.5px !important;
    border-radius: 8px !important;
    padding: 0.65rem 0 !important;
    width: 100% !important;
    transition: opacity 0.15s !important;
}
.run-btn > button:hover { opacity: 0.85 !important; }

/* ── Textarea — kill Streamlit's yellow session-state highlight ── */
.stTextArea textarea,
.stTextArea textarea:focus,
.stTextArea textarea:active,
[data-baseweb="textarea"] textarea,
[data-baseweb="textarea"] > div,
.stTextArea [data-baseweb="base-input"],
.stTextArea [data-baseweb="base-input"]:focus-within {
    background: #fff !important;
    background-color: #fff !important;
    border: 1.5px solid #ccc !important;
    border-radius: 8px !important;
    font-family: 'DM Mono', monospace !important;
    font-size: 0.82rem !important;
    color: #1a1a1a !important;
    line-height: 1.7 !important;
    box-shadow: none !important;
    caret-color: #1a1a1a !important;
}
.stTextArea textarea:focus {
    border-color: #1a1a1a !important;
}
/* Kill yellow on ALL input widgets (Streamlit dirty-state tint) */
[data-baseweb="base-input"] { background: #fff !important; }
input, textarea, select { background: #fff !important; color: #1a1a1a !important; }

/* ── Selectbox ── */
[data-baseweb="select"] > div,
[data-baseweb="select"] span,
[data-baseweb="select"] input {
    background: #fff !important;
    color: #1a1a1a !important;
    font-family: 'DM Mono', monospace !important;
    font-size: 0.78rem !important;
    border-color: #ccc !important;
}
[data-baseweb="popover"] li {
    font-family: 'DM Mono', monospace !important;
    font-size: 0.78rem !important;
    color: #1a1a1a !important;
}

/* ── Checkbox ── */
.stCheckbox label,
.stCheckbox label p,
.stCheckbox span {
    font-family: 'DM Mono', monospace !important;
    font-size: 0.78rem !important;
    color: #333 !important;
}

/* ── Section & general text ── */
p, span, div, label {
    color: inherit;
}
.stMarkdown p { color: #1a1a1a; }

/* ── Image display ── */
.img-frame {
    background: #fff;
    border: 1.5px solid #e0ddd6;
    border-radius: 10px;
    padding: 10px;
    margin-bottom: 0.7rem;
}
.img-meta {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
    margin-top: 0.5rem;
}
.img-tag {
    font-size: 0.68rem;
    background: #f0ede7;
    border: 1px solid #ddd;
    color: #666;
    padding: 3px 9px;
    border-radius: 4px;
}
.img-tag b { color: #1a1a1a; }

/* ── Output panel ── */
.out-panel {
    background: #1a1a1a;
    border-radius: 10px;
    padding: 1.6rem 1.8rem;
    min-height: 300px;
    max-height: 580px;
    overflow-y: auto;
    color: #e8e5df;
    font-size: 0.8rem;
    line-height: 1.75;
    white-space: pre-wrap;
    word-break: break-word;
}
.out-empty {
    color: #444;
    font-size: 0.78rem;
    display: flex;
    align-items: center;
    justify-content: center;
    height: 260px;
    text-align: center;
    line-height: 2;
}
.out-stats {
    display: flex;
    gap: 10px;
    margin-top: 0.75rem;
}
.stat-tag {
    font-size: 0.68rem;
    background: #fff;
    border: 1.5px solid #e0ddd6;
    color: #666;
    padding: 3px 10px;
    border-radius: 4px;
}
.stat-tag b { color: #1a1a1a; }

/* ── Spinner override ── */
.stSpinner > div { border-top-color: #c8f53c !important; }

/* ── Thinking badge ── */
.think-badge {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    font-size: 0.68rem;
    background: #c8f53c22;
    border: 1px solid #c8f53c66;
    color: #5a6e00;
    padding: 3px 10px;
    border-radius: 4px;
    margin-bottom: 0.6rem;
}

hr { border-color: #e0ddd6 !important; margin: 2.5rem 0 !important; }
</style>
""", unsafe_allow_html=True)

# ── Quick prompts list ─────────────────────────────────────────────────────────
QUICK_PROMPTS = [
    ("⬡ Parse → Markdown",      "Parse this document to Markdown."),
    ("⊞ Extract table",          "Extract all tables from this image and format them as Markdown tables."),
    ("{ } Key info → JSON",      "Extract key information from this document. Return as JSON with relevant fields."),
    ("∑ Numbers & dates",        "Extract all numbers, amounts, dates, and monetary values from this image."),
    ("? Document Q&A",           "What is the main content of this document? Give a concise summary."),
    ("⌖ Layout analysis",        "Analyze the layout of this document: identify all sections, headings, and structure."),
]

# ── Model loading (cached) ─────────────────────────────────────────────────────
@st.cache_resource(show_spinner=False)
def get_model():
    return OCR()

# ── Top bar ────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="topbar">
  <div class="topbar-title">Qianfan<span>OCR</span></div>
  <div class="topbar-meta">baidu/Qianfan-OCR · 4B params · 192 languages · #1 OmniDocBench v1.5</div>
</div>
""", unsafe_allow_html=True)

# ── Two-column layout ──────────────────────────────────────────────────────────
col_l, col_r = st.columns([1, 1], gap="large")

# ════════════════ LEFT COLUMN ════════════════
with col_l:

    # 01 — Upload
    st.markdown('<div class="sec-label">01 — Upload image</div>', unsafe_allow_html=True)
    uploaded = st.file_uploader(
        "image",
        type=["png", "jpg", "jpeg", "webp", "bmp", "tiff"],
        label_visibility="collapsed",
    )

    pil_img = None
    tmp_path = None

    if uploaded:
        pil_img = Image.open(uploaded).convert("RGB")
        w, h = pil_img.size

        st.markdown('<div class="img-frame">', unsafe_allow_html=True)
        st.image(pil_img, use_container_width=True)
        st.markdown('</div>', unsafe_allow_html=True)

        st.markdown(f"""
        <div class="img-meta">
          <div class="img-tag"><b>{w}×{h}</b> px</div>
          <div class="img-tag"><b>{uploaded.type.split("/")[1].upper()}</b></div>
          <div class="img-tag">{uploaded.name}</div>
          <div class="img-tag"><b>{round(uploaded.size/1024, 1)}</b> KB</div>
        </div>
        """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # 02 — Quick prompts
    st.markdown('<div class="sec-label">02 — Quick prompts</div>', unsafe_allow_html=True)
    cols = st.columns(3)
    for i, (label, prompt_text) in enumerate(QUICK_PROMPTS):
        with cols[i % 3]:
            if st.button(label, key=f"qp_{i}", use_container_width=True):
                st.session_state["user_prompt"] = prompt_text

    st.markdown("<br>", unsafe_allow_html=True)

    # 03 — Custom prompt
    st.markdown('<div class="sec-label">03 — Prompt</div>', unsafe_allow_html=True)
    prompt = st.text_area(
        "prompt",
        value=st.session_state.get("user_prompt", "Parse this document to Markdown."),
        key="user_prompt",
        height=120,
        label_visibility="collapsed",
        placeholder="Type your prompt here, or pick one above…",
    )

    # Options row
    opt_l, opt_r = st.columns([1, 1])
    with opt_l:
        thinking = st.checkbox("Layout-as-Thought (thinking mode)", value=False)
    with opt_r:
        max_tokens = st.selectbox(
            "Max tokens",
            [512, 1024, 2048, 4096, 8192],
            index=2,
            label_visibility="visible",
        )

    st.markdown("<br>", unsafe_allow_html=True)

    # Run button
    st.markdown('<div class="run-btn">', unsafe_allow_html=True)
    run = st.button("RUN  ›", use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

# ════════════════ RIGHT COLUMN ════════════════
with col_r:

    st.markdown('<div class="sec-label">04 — Output</div>', unsafe_allow_html=True)

    result_area  = st.empty()
    stats_area   = st.empty()
    copy_area    = st.empty()

    if run:
        if not uploaded:
            result_area.warning("Upload an image first.")
        elif not prompt.strip():
            result_area.warning("Enter a prompt.")
        else:
            # Save upload to temp file (OCR.load_image needs a file path)
            suffix = os.path.splitext(uploaded.name)[-1] or ".jpg"
            with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
                tmp.write(uploaded.getvalue())
                tmp_path = tmp.name

            with st.spinner("Loading model & running inference…"):
                try:
                    ocr = get_model()

                    final_prompt = prompt.rstrip() + ("<think>" if thinking else "")

                    t0 = time.time()
                    result = ocr.infer_model(tmp_path, final_prompt, max_token=max_tokens)
                    elapsed = round(time.time() - t0, 2)

                    result_area.markdown(
                        f'<div class="out-panel">{result}</div>',
                        unsafe_allow_html=True,
                    )

                    think_badge = (
                        '<span class="think-badge">⬡ Layout-as-Thought ON</span>'
                        if thinking else ""
                    )
                    char_count = len(result)
                    stats_area.markdown(f"""
                    {think_badge}
                    <div class="out-stats">
                      <div class="stat-tag">time <b>{elapsed}s</b></div>
                      <div class="stat-tag">max tokens <b>{max_tokens}</b></div>
                      <div class="stat-tag">output chars <b>{char_count}</b></div>
                    </div>
                    """, unsafe_allow_html=True)

                    copy_area.code(result, language="markdown")

                except Exception as e:
                    result_area.error(f"Error: {e}")
                finally:
                    if tmp_path and os.path.exists(tmp_path):
                        os.unlink(tmp_path)

    else:
        result_area.markdown("""
        <div class="out-panel">
          <div class="out-empty">
            Upload an image<br>choose a prompt<br>hit RUN ›
          </div>
        </div>
        """, unsafe_allow_html=True)

# ── Footer ─────────────────────────────────────────────────────────────────────
st.markdown("<hr>", unsafe_allow_html=True)
st.markdown("""
<div style="font-size:0.65rem;color:#aaa;text-align:center;letter-spacing:1px;">
  QIANFAN-OCR · APACHE 2.0 · BAIDU · 93.12 OMNIDOCBENCH · 192 LANGUAGES
</div>
""", unsafe_allow_html=True)
